### ISSUE TITLE
Add ability to specify a `ref`

### ISSUE THREAD

**Issue by mmlngl** [holidaycheck/react-google-tag-manager#11]
Add ability to specify a `ref` attr so we don't have to find the node in the DOM.

i.e. so we don't have to write:

```
if (!window[dataLayerName]) {
    const gtmScriptNode = document.getElementById(scriptId);
    eval(gtmScriptNode.textContent);
}
```

Instead, we can write:

```
if (!window[dataLayerName]) {
    const gtmScriptNode = this.refs.script;
    eval(gtmScriptNode.textContent);
}
```

**Comment by lxanders** [comment]
Thanks for your suggestion @mmmoli. 

I do think however that you might have misunderstood the scope of this project. The example component that we are describing in the [readme](https://github.com/holidaycheck/react-google-tag-manager/blob/master/README.md) is a component that you would have to implement yourself. You could totally set any refs in there that you want to have. This project is focussed on the underlying google tag manager parts (e.g. the gtm script). 

I experimented once with exposing a component but ran into problems like having to know too much detail about the context where it would have been used so I dropped it again. I still think that exporting a real component would be possible but it involves quite much work, that nobody here was willing to / had the time to do.

Maybe our documentation is not clear enough on the fact of having to implement the component yourself (and using our exported functionality). Do you have an idea what might have helped you in making my point from above more clear?

**Comment by mmlngl** [comment]
No, I get that.

This is a very tiny change I'm proposing.

I'm using the [`scriptAsReact`](https://github.com/holidaycheck/react-google-tag-manager/blob/master/src/index.jsx#L16). It would be good to configure a `ref` attr for the `script` element it create because that'll help refer to it later one.

The problem is that I can't do this:

```
render() {
    const gtm = {...}
    let Script = gtm.scriptAsReact()
    Script.ref = 'gtm-script'
    return (
        <Script>
    );
}


```

**Comment by lxanders** [comment]
As far as I understand this, this would however not be accessible as `this.refs.refToTheScript` in your own Google Tag Manager component so it would not achieve what you want to achieve IMO. 

Apart from that you would normally not write anything like `Component.anything = 'something'` in react. If you provide a ref to a child component of a component it works like this:

```
MyComp extends React.Component {
    doSomething(event) {
        this.refs.myOutput.value = event.target.value.toUpperCase();
    }

    render() {
        return (
            <div>
                <input type='text' onChange={this.doSomething.bind(this)} />
                <input type='text' ref='myOutput' disabled />
            </div>
        );
    }
}
```

This would access and modify the output field with the ref `myOutput` which is definitely not available otherwise in the event context.

**Comment by lxanders** [comment]
I'm closing this for now. If you want to add something or have the feeling that I misunderstood you, please feel free to make your point.
