### ISSUE TITLE
Component doesn't work

### ISSUE THREAD

**Issue by mawek** [holidaycheck/react-google-tag-manager#2]
I'm trying to  use this component (react: 0.14.2) as shown in example, but although it is rendered properly (I can see all the code in the DOM), google tag manager doesn't work. Google tag manager code is not even downloaded, nor the google analytics code is downloaded.

**Comment by lxanders** [comment]
Hi @mawek. Could you provide a minimal example that I could use to reproduce your problems? Or maybe one of these points already address your problem:
- You might have forgotten to provide a google tag manager id
- You might have something like the analytics opt out plugin activated in your browser or something like this

I just checked our usage of this module and it is working for me locally and on our production website. The google tag manager script is downloaded and I checked with the [dataslayer chrome plugin](https://chrome.google.com/webstore/detail/dataslayer/ikbablmmjldhamhcldjjigniffkkjgpo) that events are fired. 

We are currently using `"react": "0.14.2"` and `"react-google-tag-manager": "1.0.1"`.

**Comment by mawek** [comment]
Thanks for quick response. I have correct ID set, the component is rendered but it doesn't do anything.
The gtm component is in the DOM:
![elements](http://i.imgur.com/Oyutmfm.png)

i can also inspect it using react devtools
![react-dev-tools](http://i.imgur.com/pODTRpV.png)

but it doesn't load the gtm/ga code
![network](http://i.imgur.com/zT3k2ca.png)

also dataslayer is empty
![dataslayer](http://i.imgur.com/MSPcnGT.png)

**Comment by lxanders** [comment]
Yeah you're right, this result definitely looks wrong.

I just replaced our google tag manager component with the one described in the `README.md`, configured our GTM id and removed the configuration of a custom layer and tried the behavior once again. I get a request to `http://www.googletagmanager.com/gtm.js?id=GTM-123456` (note: I replaced the GTM id here just to not expose our id) which returns with status 200 & the appropriate gtm script. 

I currently think that there might still be an error in your tag manager component (the one that uses this package). Could you post your implementation of that component? Maybe I can directly find the problem or be at least able to reproduce the behavior.

**Comment by mawek** [comment]
My implementation is pretty simple

```
import { Component} from 'react';
import gtmParts from 'react-google-tag-manager'

export default class GoogleTagManager extends Component {

    render() {
        const gtm = gtmParts({
            id: 'GTM-PXTDWS'
        });

        return (
            <div id="gtm">
                {gtm.noScriptAsReact()}
                {gtm.scriptAsReact()}
            </div>
        );
    }
}
```

and i include it as

```
...
return (
            <div className='gdc-data-content'>
                <GoogleTagManager/>
...
```

**Comment by lxanders** [comment]
Your `GoogleTagManager` implementation looks right on the first look. I will rule that out as the error source for now.

For me it looks currently as if all parts of the gtm integration are loaded up correctly until the point where an async script for loading `gtm.js` should be created. This async script should look like this:

```
<script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-<yourId>"></script>
```

It is created by the immediately invoked cryptical function that you showed in the screenshot containing your DOM.

Please check if you have this script in your DOM. I looked at it and it is not visible so it has to be either part of your `head` - which is collapsed - or it is not present. There might still be some browser addons involved that block that from happening. Maybe some errors in your browser console show something about this?

**Comment by mawek** [comment]
the mentioned script tag is not there (not in the header and not elsewhere). 
If I put breakpoint inside of my `GoogleTagManager` component (in the render method), it stops there.  Also if I put breakpoint in the `buildParts` method of `react-google-tag-manager` extensions, it stops there. But if I put breakpoint directly in the script variable of build_parts method ([like here for example](https://github.com/holidaycheck/react-google-tag-manager/blob/master/src/build_parts.js#L16)) - it is ignored. Looks like that code is never interpreted by browser.

**Comment by lxanders** [comment]
This starts more and more to look like a problem in the browser / your browser configuration. The script you are talking about is the Google Tag Manager standard script as documented in the [Google Tag Manager documentation](https://developers.google.com/tag-manager/quickstart). If this is not executed your browser / setup does not execute a standard `script` tag which is very strange. So I will point once more to extensions you might have installed in your browser or errors in your browser console.

I e.g. just tested with an adblocker enabled and got an error on console where this script was blocked (and the async script was therefore not created).

**Comment by mawek** [comment]
I also tried it in firefox and it behaves the same way (as in chrome). Also if i include gtm code manually in my index.html file - it works just fine.

**Comment by FQ400** [comment]
Hi @mawek,
can you please provide a screenshot of your chrome console output?

**Comment by mawek** [comment]
console contains no errors/warnings

![console](http://i.imgur.com/DdGzpj1.png)

**Comment by lxanders** [comment]
As it is right now reproducable for me I will create a somewhat minimal example app to check if the component has problems there. Unfortunately I won't have time for this until tomorrow. I will post here once this is done or if another idea comes to my mind.

**Comment by lxanders** [comment]
Hi @mawek. I'm finally able to reproduce the problem (after I created a very minimalistic react application). It seems that purely client side rendered react applications don't currently work as intended. Thanks for reporting that :+1:. We will try to come up with a solution soon (as in: "I don't have very much time right now but will try to get this flying as soon as possible as its a major bug").

**Comment by mawek** [comment]
Thank you very much for your time!

**Comment by lxanders** [comment]
To at least come back to you @mawek: I was sick last week and are a bit in a pre christmas stress phase so there was no visible progress until now. 

Apart from that: Analysing this project and finding my way into it I found some things I really want to change. Hopefully I will be able to finish my first prototype soon. Stay tuned, you might like the new version (that does not have the bug you mentioned anymore) more, as e.g. one of the features I'm planning is directly exposing a `<GoogleTagManager>` component that can be used without having to write one that uses parts of this module.
