### ISSUE TITLE
console error Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by A11oW** [holidaycheck/react-google-tag-manager#20]
Hello. Thanks for component, but I have error in console, when I try use his.
error in this line `eval(gtmScriptNode.textContent);`

error happens because `gtmScriptNode.textContent` have html tags

maybe eval only script content?
`const gtmScriptNode = document.getElementById(scriptId).getElementsByTagName('script')[0]`

**Comment by A11oW** [comment]
error in this line `eval(gtmScriptNode.textContent);`

**Comment by FQ400** [comment]
Hi @A11oW, I will check you issue tomorrow and come back to you.

**Comment by cidevant** [comment]
+1

**Comment by cidevant** [comment]
In README author shows us how to use react-gtm. If you "blind" copied it - bug might be hidden here.
Look closely to render method:

```
      <div id={scriptId || 'react-google-tag-manager-gtm'}>
        {gtm.noScriptAsReact()}
        {gtm.scriptAsReact()}
      </div>
```

You see that on the first place is called method `gtm.noScriptAsReact()`, which does nothing, when  client browsering web with enabled js. On the server it renders `<iframe>` and then client's browser is trying to js eval this `<iframe>` - big bada boom!)

Maybe this error wont happen, if your app is not isomorphic. 

Cheers.

**Comment by cidevant** [comment]
Maybe this piece of code can help you) Just edit your `render` method like this

```
    return (
      <div>
        <div>{gtm.noScriptAsReact()}</div>
        <div id={scriptId || 'react-google-tag-manager-gtm'}>
          {gtm.scriptAsReact()}
        </div>
      </div>
    );
```

**Comment by diffractometer** [comment]
+1 @cidevant, but I had to use `this.props.scriptId`

```
    return (
      <div>
        <div>{gtm.noScriptAsReact()}</div>
        <div id={this.props.scriptId || 'react-google-tag-manager-gtm'}>
          {gtm.scriptAsReact()}
        </div>
      </div>
    );

```

**Comment by cidevant** [comment]
@diffractometer You are right :) I used this before `return` method:

```
const { scriptId } = this.props;
```

**Comment by positivew** [comment]
I also stumbled upon this problem. Could you update the example in README to be like @cidevant suggested?

**Comment by gf3** [comment]
wouldn't it be cleaner to use a `ref` instead of an `id`?

**Comment by FQ400** [comment]
I think this depends on your use case.
