### ISSUE TITLE
Why does this just contain the parts, and not the actual component?

### ISSUE THREAD

**Issue by reggi** [holidaycheck/react-google-tag-manager#25]
Really curious why this just contains the parts for google tag manager, and not the actual component.

**Comment by lo1tuma** [comment]
What do you mean by the actual component?

**Comment by FQ400** [comment]
@reggi The _actual_ component would have to consider if it runs on the server or on the client. 
The time we developed it, there was no need to implement it. Feel free to add a PR. 😄
