### ISSUE TITLE
when are dataLayer pushed events invoked?

### ISSUE THREAD

**Issue by quarryman** [holidaycheck/react-google-tag-manager#34]
Hi there.
Can you plz clarify shortly the flow for calling pageView event with GTM?
Given I followed your setup, created component and want to add pageView event using dataLayer.push({ 'event': 'VirtualPageview', 'url': 'someurl'}) on button click.
dataLayer.push() adds my event to dataLayer tags array, but it's unclear what causes them to be pushed to GTM server and how GTM detects new event was added if i add it after your component was rendered?
Thanx

**Comment by lo1tuma** [comment]
Hi,

I don’t think your question is related to this module. `react-google-tag-manager` is only a way to integrate the GTM snippet within a react application. Pushing to the `dataLayer` means you are using the GTM API directly, so you should check out the GTM documentation.

**Comment by quarryman** [comment]
I hoped to get clearer understanding what this module component does. Caz pushing events to dataLayer as its told in GTM API doesn't results in anything being sent to server

**Comment by FQ400** [comment]
Hi @quarryman,

this component integrates the javascript snippet from **G**oogle **T**ag **M**anager into your react application using the ID of your GTM suite. With this in place, Google's snippet creates an array like global object called `dataLayer`.
Based on your application, you have to write a function that calls `dataLayer.push({ 'event': 'VirtualPageview', 'url': 'someurl'})` which is bound to your button click. Listen in GTM to that event and push it to your web tracking solution.

In the background Google will somehow sync the content, you pushed to the dataLayer, to their servers. I don't know how exactly, but when GTM is integrated your network tab in the browser will show `collect` image requests, which talk to Google.

There are also a bunch of extension out there that visualize GTM activity. We use `DataSlayer` for Chrome.

I close this issue, cause @lo1tuma is right, out of scope.
