### ISSUE TITLE
No LICENSE information.

### ISSUE THREAD

**Issue by mvandiest** [holidaycheck/react-google-tag-manager#4]
Would love to use the package, can a LICENSE be added? MIT preferably... :)

**Comment by lxanders** [comment]
Cool that it sounds interesting to you @mvandiest! Thanks for pointing that out. Actually there is already a (somewhat hidden) license information to this project. You can find it in the [package.json](https://github.com/holidaycheck/react-google-tag-manager/blob/master/package.json#L24). Its under the extremely permissive [Beerware license](https://fedoraproject.org/wiki/Licensing/Beerware). 

This license is comparable to licenses like the MIT but has the additional small remark that if you really like the software and at some point meet one of the creators you can (but absolutely don't have to) buy them (or yourself) a beer :blush:. I will however add a license file so the license is not only mentioned but shipped with the module.

**Comment by lxanders** [comment]
Now thinking once more about it: While this license is fun and makes the intent clear ('just use this piece of software in any way you want to') I think it might be better to use a better known license. I will create a pull request with the MIT license.

**Comment by mvandiest** [comment]
@lxanders thx! I'll still honor the beerware license as well ;)
