### ISSUE TITLE
How is the `additionalEvents` property meant to be used?

### ISSUE THREAD

**Issue by gf3** [holidaycheck/react-google-tag-manager#49]
Are you able to provide a simple example of how one might use the `additionalEvents` property?

**Comment by FQ400** [comment]
It should be an javascript object. See the [test case](https://github.com/holidaycheck/react-google-tag-manager/blob/master/test/src/build_parts.spec.js#L35).

I will update the test case with a `real world` example.

**Comment by FQ400** [comment]
Here are the docs from GTM: https://developers.google.com/tag-manager/devguide#events

**Comment by gf3** [comment]
are the events in `additionalEvents` meant to be pushed on `componentDidMount`?

**Comment by FQ400** [comment]
Yes.
