### ISSUE TITLE
Rendering the component to be a direct descendant of the body tag

### ISSUE THREAD

**Issue by gmenih** [holidaycheck/react-google-tag-manager#51]
Google's guidelines say that the scripts should be direct descendants of the `<body>` tag.

Is there a way to place these to be outside the root of the app?

**Comment by FQ400** [comment]
The repo only contains the snippet where you put it, is up to you.

Maybe this article of [Rendering React components to the document body](http://jamesknelson.com/rendering-react-components-to-the-document-body/) helps?
