### ISSUE TITLE
Using ReactGTM with react-router

### ISSUE THREAD

**Issue by spetex** [holidaycheck/react-google-tag-manager#53]
Hello,
I have a simple React/Redux application which uses react router for syncing the URL. I also have react-google-tag-manager in my app. Unfortunately my GA does not track URLs while transitioning in the app. In order to change the URL I have to force refresh the page which obviously forces the GTM component to re-render.

My thinking is force the GTM component to re-render each time route transition occurs.

Is there a simple solution which I am missing?

Thanks!

**Comment by FQ400** [comment]
Hey @spetex,

the Google Tag Manager and Google Analytics are two different things. 

Assuming GTM is used to deliver GA to your page, it is possible to trigger *virtual page views* after the routing transition is done.

That should do the trick.

Regards.

**Comment by FQ400** [comment]
Appears to be fine ...
