### ISSUE TITLE
React v16 gives a peer dependency warning

### ISSUE THREAD

**Issue by Redmega** [holidaycheck/react-google-tag-manager#66]
Seems to work fine. Time to update the peer deps in the `package.json` now that react fiber is officially released?

**Comment by ravikiran438** [comment]
@HeeL Can you please create a release tag for this change. Thanks!

**Comment by kevcenteno** [comment]
@HeeL Can we get this released, please?

**Comment by HeeL** [comment]
@kevcenteno yes, this will be released soon
