### ISSUE TITLE
Broken when no previewVariables is defined

### ISSUE THREAD

**Issue by goncharov** [holidaycheck/react-google-tag-manager#68]
Hello there. After update to 2.2.0 we've got error when no previewVariables is defined. `scriptAsReact `generates code like this with broken concatenation
```
j.src='//www.googletagmanager.com/gtm.js?id='+i+dl
+;
f.parentNode.insertBefore(j,f);
```

**Comment by HeeL** [comment]
I will have a look today and publish new version if needed

Am 03.11.2017 4:25 nachm. schrieb "Stanislav Goncharov" <
notifications@github.com>:

**Comment by selaux** [comment]
I see the issue (and we also experience it in our project). Will create a PR.

**Comment by HeeL** [comment]
Version 2.2.1 has been released. Thanks for reporting/fixing
